Draft for autoupdates

diff --git a/41atlas b/41atlas
--- a/41atlas
+++ b/41atlas
@@ -25,6 +25,25 @@ if [[ "$session_id" ]] ;then
 fi
 }
 
+execute_autoupdates(){
+# if ! grep -q "version $uver" /system/bin/update_mad.sh; then
+    # download https://raw.githubusercontent.com/Map-A-Droid/MAD-ATV/master/update_mad.sh /system/bin/update_mad.sh
+    # chmod +x /system/bin/update_mad.sh
+# fi
+# if ! grep -q "version $pver" /system/bin/pingreboot.sh; then
+     # download https://raw.githubusercontent.com/Map-A-Droid/MAD-ATV/master/pingreboot.sh /system/bin/pingreboot.sh
+     # chmod +x /system/bin/pingreboot.sh
+# fi
+# #if ! grep -q "version $nver" /system/bin/nfs_install.sh; then
+# #    download https://raw.githubusercontent.com/Map-A-Droid/MAD-ATV/master/nfs_install.sh /system/bin/nfs_install.sh
+# #    chmod +x /system/bin/nfs_install.sh
+# #fi
+# ! [[ -f /sdcard/disableautopogoupdate ]] && sh -x /system/bin/update_mad.sh -p
+# ! [[ -f /sdcard/disableautopogodroidupdate ]] && sh -x /system/bin/update_mad.sh -wd
+# ! [[ -f /sdcard/disableautorgcupdate ]] && sh -x /system/bin/update_mad.sh -wr
+}
+
+
 #don't add it for execution as long as no one else is having issues with wrong language
 set_android_language() {
 if ! [[ "$(getprop persist.sys.locale)" == "en-US" ]] ;then
@@ -172,6 +191,7 @@ if [ ! -d "$DIR" ]; then
   echo "${DIR} doesn't exist, installing eMagisk"
   /system/bin/curl -s -k -L -o /sdcard/eMagisk.zip https://github.com/Astu04/eMagisk/releases/download/latest/eMagisk.zip
   su -c 'magisk --install-module /sdcard/eMagisk.zip'
+  cachereboot=1
 fi
 DIR="/data/adb/modules/ssh"
 if [ ! -d "$DIR" ]; then
@@ -188,6 +208,7 @@ if [ ! -d "$DIR" ]; then
 	su -c chmod 600 /data/ssh/shell/.ssh/authorized_keys
 	su -c "sed -i 's@#StrictModes yes@StrictModes no@g' /data/ssh/sshd_config"
   fi
+  cachereboot=1
 elif [[ ! -f /data/ssh/root/.ssh/authorized_keys ]] ;then # if ssh module is installed but there are no keys
   if [[ -f /sdcard/authorized_keys ]] ;then
 	su -c cp /sdcard/authorized_keys /data/ssh/root/.ssh/authorized_keys
@@ -196,8 +217,13 @@ elif [[ ! -f /data/ssh/root/.ssh/authorized_keys ]] ;then # if ssh module is ins
 	su -c chmod 600 /data/ssh/shell/.ssh/authorized_keys
 	su -c "sed -i 's@#StrictModes yes@StrictModes no@g' /data/ssh/sshd_config"
   fi
+  cachereboot=1
 fi
-
+if (( "$cachereboot" )) ;then
+    log_msg "2" "Rebooting into recovery mode for required installations"
+    echo '--wipe_cache' >> /cache/recovery/command
+    reboot recovery
+fi
 execute_autoupdates
 mount -o remount,ro /system
 
